# Generated by Django 5.0.6 on 2024-07-16 14:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_chatmessage_managers_and_more'),
    ]

    operations = [
    ]
