# Generated by Django 5.0.6 on 2024-07-16 16:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_add_test_data'),
        ('chat', '0003_auto_20240716_1422'),
    ]

    operations = [
    ]
